Use -P to fix with_deps scenario
Now we can install extra packages into the generated GOPATH, use that
to fix the with_deps scenario.

Also, test each scenario with withmock and mocktest.

diff --git a/scenarios/test b/scenarios/test
--- a/scenarios/test
+++ b/scenarios/test
@@ -4,10 +4,28 @@ cd "$(dirname "$0")"
 
 ret=0
 
-for f in */test; do
+echo -e "\e[33;1mwithmock\e[0m"
+echo -e "========"
+for f in */test.withmock; do
     d=$(dirname "$f")
     echo -n "${d}: "
-    (cd $d; ./test) >> test.log 2>&1
+    (cd $d; ./test.withmock) >> test.log 2>&1
+    if [ $? -ne 0 ]; then
+        echo -e "\e[31;1mFAIL\e[0m"
+        ret=1
+    else
+        echo -e "\e[32;1mPASS\e[0m"
+    fi
+done
+
+echo
+
+echo -e "\e[33;1mmocktest\e[0m"
+echo -e "========"
+for f in */test.mocktest; do
+    d=$(dirname "$f")
+    echo -n "${d}: "
+    (cd $d; ./test.mocktest) >> test.log 2>&1
     if [ $? -ne 0 ]; then
         echo -e "\e[31;1mFAIL\e[0m"
         ret=1
