change the output of scenarios tests script
The list of test is getting longer, and this new output provides a
more compact view.

diff --git a/scenarios/test b/scenarios/test
--- a/scenarios/test
+++ b/scenarios/test
@@ -4,37 +4,38 @@ cd "$(dirname "$0")"
 
 ret=0
 
-echo -e "\e[33;1mwithmock\e[0m"
+echo -e "\e[33;1mscenrios\e[0m"
 echo -e "========"
-echo "=== withmock ===" > test.log
-for f in */test.withmock; do
-    d=$(dirname "$f")
-    echo "--- ${d} ---" >> test.log
-    echo -n "${d}: "
-    (cd $d; ./test.withmock) >> test.log 2>&1
-    if [ $? -ne 0 ]; then
-        echo -e "\e[31;1mFAIL\e[0m"
-        ret=1
-    else
-        echo -e "\e[32;1mPASS\e[0m"
+echo -e "                    withmock\tmocktest"
+for d in $(ls -vd *); do
+    if [ ! -d "${d}" ]; then
+        continue
     fi
-done
-
-echo
-
-echo -e "\e[33;1mmocktest\e[0m"
-echo -e "========"
-echo "=== mocktest ===" >> test.log
-for f in */test.mocktest; do
-    d=$(dirname "$f")
-    echo "--- ${d} ---" >> test.log
-    echo -n "${d}: "
-    (cd $d; ./test.mocktest) >> test.log 2>&1
-    if [ $? -ne 0 ]; then
-        echo -e "\e[31;1mFAIL\e[0m"
-        ret=1
+    printf "%-20s" "${d}:"
+    echo "=== ${d} ===" >> test.log
+    if [ -x "${d}/test.withmock" ]; then
+        echo "--- withmock ---" > test.log
+        (cd $d; ./test.withmock) >> test.log 2>&1
+        if [ $? -ne 0 ]; then
+            echo -ne "\e[31;1mFAIL\e[0m\t"
+            ret=1
+        else
+            echo -ne "\e[32;1mPASS\e[0m\t"
+        fi
     else
-        echo -e "\e[32;1mPASS\e[0m"
+        echo -ne "\e[33;1mSKIP\e[0m\t"
+    fi
+    if [ -x "${d}/test.mocktest" ]; then
+        echo "--- mocktest ---" > test.log
+        (cd $d; ./test.mocktest) >> test.log 2>&1
+        if [ $? -ne 0 ]; then
+            echo -e "\e[31;1mFAIL\e[0m"
+            ret=1
+        else
+            echo -e "\e[32;1mPASS\e[0m"
+        fi
+    else
+        echo -e "\e[33;1mSKIP\e[0m"
     fi
 done
 
